# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
    ]
